server:
  context-path: /cloud-service-hive
  port: 8083
debug: true
spring:
  datasource:
    driver-class-name: org.apache.hive.jdbc.HiveDriver
    url: jdbc:hive2://172.31.100.192:10000
    username: hdfs
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: cloud-service-hive
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:1111/register-centre/eureka/
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
